paths:
  raw_data: data/raw
  processed_data: data/processed

pipeline:
  expand_times: 10
  output_path: data/processed/online_retail_full.parquet 

data_sources:

  - name: online_retail
    url: https://archive.ics.uci.edu/ml/machine-learning-databases/00352/Online%20Retail.xlsx

  - name: exchange_rates
    url: https://api.exchangerate.host/latest

  - name: country_metadata
    path: data/raw/country_metadata.csv